[server]
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#10A37F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F8"
textColor = "#353740"
font = "sans serif"
